Repository institute-atri/wastrap, pull requests merged in 2024-03, with the labels that each got.

#11 feat: architectural design
  .gitignore
  README.md
  cli/cmd.go
  go.mod
  go.sum
  internal/banner/banner.go
  internal/engine/engine.go
  main.go
Labels: enhancement, help wanted

#12 feat/#9: create module internal of Update/Upgrade
  go.mod
  go.sum
  internal/config/config.yaml
  main.go
  update/check.go
  update/getting.go
Labels: enhancement

#16 feat(ci): create CI/CD
  .github/workflow/ci.yml
  go.mod
Labels: enhancement

#15 feat(deps): add dependabot
  .github/dependabot.yml
Labels: enhancement

#18 fix(ci): implement race detection and coverage in tests
  .github/workflows/ci.yml
  main.go
Labels: bug

#19 fix(ci): Simplify shell selection in GitHub Actions CI configuration
  .github/workflows/ci.yml
Labels: bug

#21 refactor/#20: increase the purity of update package functions
  update/check.go
  update/getting.go
Labels: enhancement

#13 feat/#4: create cli with Cobra
  cli/cli.go
  cli/cmd.go
  cli/cmd/root.go
  main.go
Labels: enhancement

#27 feat(#26): update go.mod with the new gnet commit
  go.sum
Labels: enhancement

#35 feat(tests): create unit tests for update package internal
  internal/update/check.go
  internal/update/getting.go
  internal/update/updatecheck_test.go
  internal/update/updategetting_test.go
  main.go
Labels: enhancement

#42 feat: create package for identify version wordpress site target
  go.mod
  go.sum
  main.go
  tools/validator/wordpress.go
Labels: enhancement

#49 feat#28: Create package users
  tools/finders/users/agressive.go
  tools/finders/users/agressive_test.go
  tools/finders/users/passive.go
  tools/finders/users/passive_test.go
Labels: enhancement

#39 feat: create identify to firewall
  go.mod
  tools/finders/firewalls/firewall.go
  tools/finders/firewalls/firewall_test.go
Labels: enhancement

#47 feat: config.go created
  internal/config/config.go
  internal/config/config.yml
  internal/config/config_test.go
Labels: enhancement
